### ISSUE TITLE
Missing file in url when updating to 2023.10.08

### ISSUE THREAD

**Issue by JManDoo** [Squidly271/fix.common.problems#9]
plugin: installing: fix.common.problems.plg
Executing hook script: pre_plugin_checks
plugin: downloading: fix.common.problems.plg ... done

plugin: downloading: fix.common.problems-2023.10.08-x86_64-1.txz ...
plugin: fix.common.problems-2023.10.08-x86_64-1.txz download failure: Invalid URL / Server error response
Executing hook script: post_plugin_checks

/var/log/syslog
Oct  8 14:01:58 unraid root: plugin: creating: /boot/config/plugins/fix.common.problems/fix.common.problems-2023.10.08-x86_64-1.txz - downloading from URL https://raw.githubusercontent.com/Squidly271/fix.common.problems/master/archive/fix.common.problems-2023.10.08-x86_64-1.txz
Oct  8 14:06:18 unraid root: plugin: creating: /boot/config/plugins/fix.common.problems/fix.common.problems-2023.10.08-x86_64-1.txz - downloading from URL https://raw.githubusercontent.com/Squidly271/fix.common.problems/master/archive/fix.common.problems-2023.10.08-x86_64-1.txz
Oct  8 14:08:21 unraid root: plugin: creating: /boot/config/plugins/fix.common.problems/fix.common.problems-2023.10.08-x86_64-1.txz - downloading from URL https://raw.githubusercontent.com/Squidly271/fix.common.problems/master/archive/fix.common.problems-2023.10.08-x86_64-1.txz

**Comment by Squidly271** [comment]
Try it again

**Comment by JManDoo** [comment]
Still the same

is this because its referencing the archive location instead of the current

it goes to https://raw.githubusercontent.com/Squidly271/fix.common.problems/master/archive/fix.common.problems-2023.10.08-x86_64-1.txz
I get a 404 as the txz file doesn't exist in that location

should it go to:
https://raw.githubusercontent.com/Squidly271/fix.common.problems/master/plugins/fix.common.problems.plg

**Comment by JManDoo** [comment]
Strong work!
![image](https://github.com/Squidly271/fix.common.problems/assets/21066923/711ff268-ab08-464c-934f-44f680d58f91)

**Comment by JManDoo** [comment]
Strong Work!
![image](https://github.com/Squidly271/fix.common.problems/assets/21066923/9bebd90a-e364-4176-92fc-3e50022caa99)
